spring.application.name=API_TFG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS}

security.jwt.secret=${JWT_SECRET}
security.jwt.exp-seconds=${JWT_EXP_SECONDS}

spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${DIALECT}
spring.jpa.hibernate.ddl-auto=${DDL}
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
server.port=${PORT}

server.servlet.context-path=${CONTEXT_PATH}
spring.jackson.mapper.accept-case-insensitive-enums=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

spring.mail.host=${HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS}