spring.application.name=API_TFG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

security.jwt.secret=${JWT_SECRET}
security.jwt.exp-seconds=${JWT_EXP_SECONDS}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
server.port=9090

server.servlet.context-path=/api
spring.jackson.mapper.accept-case-insensitive-enums=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true