name: AP TFG CI/CD with Spring Boot and PostgreSQL

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
          POSTGRES_DB: my_database_test
        ports:
          - 5432:5432
        # Esperar a que Postgres esté listo antes de iniciar los tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Permission for gradlew
      run: chmod +x gradlew

    - name: Build and Test with Gradle
      env:
        # Sobrescribimos las variables de Spring para que apunten al contenedor
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/my_database_test
        SPRING_DATASOURCE_USERNAME: user_test
        SPRING_DATASOURCE_PASSWORD: password_test
      run: ./gradlew build
